return {
    require('custom.plugins.gitsigns'),
    require('custom.plugins.which-key'),
    require('custom.plugins.telescope'),
    require('custom.plugins.lazydev'),
    require('custom.plugins.lsp'),
    require('custom.plugins.cmp'),
    require('custom.plugins.todo-comments'),
    require('custom.plugins.mini'),
    require('custom.plugins.treesitter'),
    --    require('custom.plugins.autopairs'),
    --    require('custom.plugins.lint'),
    require('custom.plugins.supermaven'),
    require('custom.plugins.harpoon'),
    require('custom.plugins.undotree'),
    require('custom.plugins.autotag'),
    require('custom.plugins.tailwindcss-colorizer'),
    require('custom.plugins.fugitive'),
    require('custom.plugins.color-theme'),
    --    require('custom.plugins.lualine'),
    require('custom.plugins.comment'),
    require('custom.plugins.luvit'),
    require('custom.plugins.dadbod'),
    require("custom.plugins.rest"),
    require("custom.plugins.oil"),
    require("custom.plugins.start-screen"),
    require('custom.plugins.conform'),
    'tpope/vim-rhubarb',
    'tpope/vim-sleuth',
}
